<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title><?php echo $file->getName() ?> mutation test reports</title>
    <link rel="stylesheet" href="<?php echo $this->resourcesDir."bootstrap.min.css"; ?>"/>
    <link rel="stylesheet" href="<?php echo $this->resourcesDir."style.css"; ?>"/>
</head>
<body>
<h1><?php echo $file->getName() ?> mutation test reports</h1>
<?php /** @var \Letscodehu\HumbugHtml\File $file */ ?>
    <div id="killed">
        <h3>Killed</h3>
        <?php foreach ($file->getKilled() as $mutant): ?>
            <?php /** @var \Letscodehu\HumbugHtml\Mutant $mutant */ ?>
            <div class="mutation">
                <table>
                    <?php echo $mutant->getDiff() ?>
                </table>
            </div>
        <?php endforeach ?>
    </div>
    <div id="uncovered">
        <h3>Uncovered</h3>
        <?php foreach ($file->getUncovered() as $mutant): ?>
            <?php /** @var \Letscodehu\HumbugHtml\Mutant $mutant */ ?>
            <div class="mutation">
                <table>
                    <?php echo $mutant->getDiff() ?>
                </table>
            </div>
        <?php endforeach ?>
    </div>
    <div id="escaped">
        <h3>Escaped</h3>
        <?php foreach ($file->getEscaped() as $mutant): ?>
            <?php /** @var \Letscodehu\HumbugHtml\Mutant $mutant */ ?>
            <div class="mutation">
                <table>
                    <?php echo $mutant->getDiff() ?>
                </table>
            </div>
        <?php endforeach ?>
    </div>
    <div id="errored">
        <h3>Errored</h3>
        <?php foreach ($file->getErrored() as $mutant): ?>
            <?php /** @var \Letscodehu\HumbugHtml\Mutant $mutant */ ?>
            <div class="mutation">
                <table>
                    <?php echo $mutant->getDiff() ?>
                </table>
            </div>
        <?php endforeach ?>
    </div>
    <div id="timeouts">
        <h3>Timeouts</h3>
        <?php foreach ($file->getTimeouts() as $mutant): ?>
            <?php /** @var \Letscodehu\HumbugHtml\Mutant $mutant */ ?>
            <div class="mutation">
                <table>
                    <?php echo $mutant->getDiff() ?>
                </table>
            </div>
        <?php endforeach ?>
    </div>
<script type="text/javascript" src="<?php echo $this->resourcesDir."jquery.min.js" ?>"></script>
<script type="text/javascript" src="<?php echo $this->resourcesDir."bootstrap.min.js" ?>"></script>
</body>
</html>