<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Humbug Html report</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo $resourcesDir."bootstrap.min.css"; ?>"/>
    <link rel="stylesheet" href="<?php echo $resourcesDir."style.css"; ?>"/>
</head>
<body>
<div class="container">
    <div class="page-header">
        <h1>Mutation Test Reports</h1>
    </div>
    <div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>
                Filename
            </th>
            <th>
                Killed
            </th>
            <th>
                Uncovered
            </th>
            <th>
                Escaped
            </th>
            <th>
                Errored
            </th>
            <th>
                Timeouts
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        /** @var \Letscodehu\HumbugHtml\Project $project */
        foreach ($project->getFiles() as $file):
            /** @var \Letscodehu\HumbugHtml\File $file */
            ?>
            <tr <?php if (count($file->getKilled()) == 0): ?>
                class="danger"
            <?php elseif (count($file->getEscaped()) == 0  && count($file->getUncovered()) == 0): ?>
                class="success"
            <?php else: ?>
                class="warning"
                <?php endif; ?>
                >
                <td>
                    <a href="files/<?php echo $file->getName() ?>.html" title="<?php echo $file->getName() ?>"><?php echo $file->getName() ?></a>
                </td>
                <td>
                    <a href="files/<?php echo $file->getName() ?>.html#killed"><?php echo count($file->getKilled()); ?></a>
                </td>
                <td>
                    <a href="files/<?php echo $file->getName() ?>.html#uncovered"><?php echo count($file->getUncovered()); ?></a>
                </td>
                <td>
                    <a href="files/<?php echo $file->getName() ?>.html#escaped"><?php echo count($file->getEscaped()); ?></a>
                </td>
                <td>
                    <a href="files/<?php echo $file->getName() ?>.html#errored"><?php echo count($file->getErrored()); ?></a>
                </td>
                <td>
                    <a href="files/<?php echo $file->getName() ?>.html#timeouts"><?php echo count($file->getTimeouts()); ?></a>
                </td>
            </tr>

        <?php endforeach ?>
        </tbody>
    </table>
        </div>
</div>
    <script type="text/javascript" src="<?php echo $resourcesDir."jquery.min.js" ?>"></script>
    <script type="text/javascript" src="<?php echo $resourcesDir."bootstrap.min.js" ?>"></script>
</body>
</html>